import * as stylex from "@stylexjs/stylex";

export const s = stylex.create({
	app: {
		maxWidth: 680,
		marginInline: "auto",
		padding: "0 20px 110px",
		"@media (max-width: 360px)": { paddingInline: 14 },
	},
	header: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 8,
		paddingBlock: 24,
	},
	brand: { display: "flex", alignItems: "center", gap: 10 },
	brandName: {
		fontSize: 20,
		fontWeight: 800,
		letterSpacing: "-0.6px",
		margin: 0,
	},
	muted: { color: "#596F7B", fontSize: 14, lineHeight: 1.6 },
	small: { fontSize: 12, lineHeight: 1.5 },
	flag: { width: 36, height: 36, flexShrink: 0 },
	badge: {
		fontSize: 11,
		fontWeight: 700,
		color: "#11786E",
		backgroundColor: "#E2F1EB",
		padding: "6px 9px",
		borderRadius: 20,
		whiteSpace: "nowrap",
	},
	title: {
		fontSize: 30,
		fontWeight: 750,
		letterSpacing: "-1px",
		lineHeight: 1.15,
		margin: "8px 0 12px",
	},
	heading: { fontSize: 19, letterSpacing: "-0.3px", margin: "0 0 10px" },
	eyebrow: {
		fontSize: 11,
		textTransform: "uppercase",
		letterSpacing: "1.4px",
		fontWeight: 800,
		margin: "0 0 12px",
		color: "#596F7B",
	},
	lead: { fontSize: 16, color: "#596F7B", lineHeight: 1.6, margin: "0 0 20px" },
	card: {
		padding: 22,
		backgroundColor: "#FFFFFF",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#DCE4E9",
		borderRadius: 16,
		marginBottom: 16,
	},
	hero: {
		backgroundColor: "#163143",
		color: "#FFFFFF",
		borderWidth: 0,
		padding: "28px 24px",
	},
	heroMuted: { color: "#C6D6DE" },
	primary: {
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		gap: 10,
		minHeight: 48,
		width: "100%",
		borderWidth: 0,
		borderStyle: "solid",
		borderRadius: 10,
		backgroundColor: "#CB2431",
		color: "#FFFFFF",
		fontWeight: 700,
		fontSize: 16,
		padding: "12px 16px",
		cursor: "pointer",
		":hover": { backgroundColor: "#AC1B27" },
		":disabled": { opacity: 0.5, cursor: "default" },
	},
	secondary: {
		backgroundColor: "#EAF0F3",
		color: "#163143",
		":hover": { backgroundColor: "#DCE6EB" },
	},
	quiet: {
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#DCE4E9",
		backgroundColor: "#FFFFFF",
		":hover": { backgroundColor: "#F2F5F7" },
	},
	split: {
		display: "grid",
		gridTemplateColumns: "1fr 1fr",
		gap: 12,
		marginBottom: 20,
	},
	stat: {
		backgroundColor: "#FFFFFF",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#DCE4E9",
		borderRadius: 12,
		padding: 16,
	},
	number: {
		fontSize: 30,
		fontWeight: 750,
		letterSpacing: "-1px",
		lineHeight: 1.2,
	},
	value: { color: "#11786E" },
	rule: {
		borderTopWidth: 3,
		borderTopStyle: "solid",
		borderTopColor: "#CB2431",
	},
	ruleGreen: {
		borderTopWidth: 3,
		borderTopStyle: "solid",
		borderTopColor: "#11786E",
	},
	row: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		gap: 12,
	},
	section: { marginBlock: 26 },
	aboutLinks: { display: "flex", flexWrap: "wrap", gap: "12px 20px" },
	stack: { display: "flex", flexDirection: "column", gap: 12 },
	rowButton: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
		gap: 14,
		width: "100%",
		textAlign: "left",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#DCE4E9",
		borderRadius: 12,
		backgroundColor: "#FFFFFF",
		padding: 18,
		cursor: "pointer",
		color: "#163143",
		minHeight: 76,
		":hover": { borderColor: "#8098A5" },
	},
	arrow: { fontSize: 24, color: "#CB2431" },
	notice: {
		color: "#596F7B",
		fontSize: 13,
		lineHeight: 1.6,
		padding: "0 2px",
		margin: "18px 0",
	},
	link: {
		color: "#19637E",
		textUnderlineOffset: 3,
		fontWeight: 600,
		overflowWrap: "anywhere",
	},
	nav: {
		position: "fixed",
		bottom: 0,
		left: 0,
		right: 0,
		zIndex: 10,
		backgroundColor: "#FFFFFF",
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: "#DCE4E9",
		paddingBottom: "env(safe-area-inset-bottom)",
	},
	navInner: {
		display: "grid",
		gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
		maxWidth: 680,
		marginInline: "auto",
	},
	navButton: {
		textDecoration: "none",
		backgroundColor: "transparent",
		borderWidth: 0,
		borderStyle: "solid",
		padding: "12px 2px 10px",
		minHeight: 64,
		color: "#596F7B",
		cursor: "pointer",
		fontSize: 11,
		fontWeight: 650,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 4,
	},
	navActive: { color: "#CB2431", backgroundColor: "#FFF6F6" },
	progress: {
		width: "100%",
		height: 6,
		accentColor: "#11786E",
		marginBlock: 12,
	},
	question: {
		fontSize: 23,
		fontWeight: 650,
		lineHeight: 1.4,
		letterSpacing: "-0.5px",
		margin: "24px 0",
	},
	choice: {
		display: "flex",
		alignItems: "flex-start",
		gap: 14,
		width: "100%",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#CCD9E0",
		borderRadius: 12,
		padding: 18,
		backgroundColor: "#FFFFFF",
		textAlign: "left",
		color: "#163143",
		fontSize: 17,
		lineHeight: 1.5,
		cursor: "pointer",
		minHeight: 62,
		":hover": { borderColor: "#163143" },
	},
	selected: {
		backgroundColor: "#EDF3F7",
		borderColor: "#163143",
		boxShadow: "inset 0 0 0 1px #163143",
	},
	correct: { backgroundColor: "#E6F3ED", borderColor: "#11786E" },
	wrong: { backgroundColor: "#FFF0F0", borderColor: "#CB2431" },
	choiceLetter: {
		fontSize: 13,
		fontWeight: 800,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#CCD9E0",
		width: 28,
		height: 28,
		borderRadius: 7,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		flexShrink: 0,
		marginTop: 1,
	},
	feedback: {
		backgroundColor: "#E6F3ED",
		borderRadius: 12,
		padding: 18,
		marginBlock: 20,
		fontSize: 15,
		lineHeight: 1.6,
	},
	error: {
		backgroundColor: "#FFF0F0",
		color: "#8C1B28",
		padding: 14,
		borderRadius: 10,
		fontSize: 14,
		lineHeight: 1.5,
		marginBlock: 12,
	},
	actions: { display: "flex", gap: 10, marginBlock: 20 },
	select: {
		width: "100%",
		minHeight: 48,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#CCD9E0",
		borderRadius: 8,
		padding: "10px 12px",
		backgroundColor: "#FFFFFF",
		color: "#163143",
		fontSize: 16,
	},
	label: { fontSize: 14, fontWeight: 700, display: "block", marginBottom: 8 },
	grid: {
		display: "grid",
		gridTemplateColumns: "repeat(auto-fit, minmax(44px, 1fr))",
		gap: 6,
		marginBlock: 14,
	},
	jump: {
		minHeight: 44,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#CCD9E0",
		borderRadius: 8,
		backgroundColor: "#FFFFFF",
		color: "#163143",
		fontSize: 13,
		cursor: "pointer",
	},
	answered: { backgroundColor: "#EAF0F3" },
	textarea: {
		width: "100%",
		minHeight: 140,
		resize: "vertical",
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: "#CCD9E0",
		borderRadius: 8,
		padding: 12,
		fontSize: 13,
		color: "#163143",
	},
	resultScore: {
		fontSize: 64,
		letterSpacing: "-3px",
		lineHeight: 1.1,
		fontWeight: 750,
		marginBlock: 12,
	},
	reviewItem: {
		paddingBlock: 18,
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: "#DCE4E9",
		fontSize: 15,
		lineHeight: 1.6,
	},
	pill: {
		fontSize: 12,
		fontWeight: 700,
		padding: "5px 10px",
		backgroundColor: "#EAF0F3",
		borderRadius: 20,
		display: "inline-block",
	},
});
